export const UPDATE_TYPE = {
  MOVE_TASK: 'MOVE_TASK',
  UPDATE_BOARD: 'UPDATE_BOARD',
  UPDATE_ASSIGNEE: 'UPDATE_ASSIGNEE',
  UPDATE_TYPE: 'UPDATE_TYPE',
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
  UPDATE_NAME: 'UPDATE_NAME',
  UPDATE_SUMMARY: 'UPDATE_SUMMARY',
  UPDATE_PRIORITY: 'UPDATE_PRIORITY',
  UPDATE_ATTACHMENT: 'UPDATE_ATTACHMENT',
  UPDATE_COVER_PHOTO: 'UPDATE_COVER_PHOTO',
};
